# Site
repository: DevGnome/Tech-Resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hugh Witchella
title: Senior Network System Administrator
email: hjwitchellacoding@gmail.com
website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: hjwcoding
github_username:  DevGnome
stackoverflow_username: "DevGnome"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: hughjwitchella
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: DevGnome
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Personal Blog
  icon: fas fa-globe
  url: https://dev.to/devgnome
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Hugh and I'm currently a student of the Flatiron School Software Engineering Flex Program. I have worked as a Special Education Classroom Aid for 5 years gaining skills in teamwork, communication and adaptability. Patience and the ability to work under pressure have been keys to my success.

  Skills I am Working in: <mark>HTML</mark>, <mark>Javascript</mark> and <mark>React</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        link: 
        # link_text: Project Website
        additional_links:
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
        description: | # this will include new lines to allow paragraphs

  #- title: Experience # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      title: The Boring Company
  #      link: boringcompany.com
  #      # link_text: boringcompany.com
  #      sub_title: Senior Network System Administrator
  #      caption: November 2017 - Present
  #      quote: >
  #        Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #      description: | # this will include new lines to allow paragraphs
  #          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seton Hill University
        caption: 2010 - 2016
        sub_title: BA History
        quote: >
        description: | # this will include new lines to allow paragraphs
        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in technology and software engineering some of my other interests and hobbies are:
      - Reading
      - Hiking
      - Gaming
      - History
      - Trivia
      

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
